// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthorPhoneNumber: typeof import('./src/components/AuthorPhoneNumber/index.vue')['default']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutList: typeof import('@nutui/nutui-taro')['List']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
  }
}
